---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - service.ntnn.github.io
  resources:
  - whoamis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.ntnn.github.io
  resources:
  - whoamis/finalizers
  verbs:
  - update
- apiGroups:
  - service.ntnn.github.io
  resources:
  - whoamis/status
  verbs:
  - get
  - patch
  - update
