# This rule is not used by the project multicluster-runtime-tester itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the service.ntnn.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multicluster-runtime-tester
    app.kubernetes.io/managed-by: kustomize
  name: whoami-editor-role
rules:
- apiGroups:
  - service.ntnn.github.io
  resources:
  - whoamis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.ntnn.github.io
  resources:
  - whoamis/status
  verbs:
  - get
